OSCILL_VERSION = 0.1.0
OSCILL_SITE = $(BR2_EXTERNAL_OSCILL_PATH)/../gui
OSCILL_SITE_METHOD = local
OSCILL_DEPENDENCIES = sdl2
ifeq ($(BR2_PACKAGE_LIBDRM),y)
OSCILL_DEPENDENCIES += libdrm
endif
OSCILL_CONF_OPTS = -DBUILD_TESTING=OFF -DSCOPE_BUILD_BENCHMARKS=OFF \
    -DSCOPE_DISPLAY_SOURCE_DIR=$(@D)/display -DSCOPE_BUILD_PREVIEW=ON -DSCOPE_ENABLE_FRAMEBUFFER=ON \
    -DSCOPE_ENABLE_DRM=$(if $(filter y,$(BR2_PACKAGE_LIBDRM)),ON,OFF) -DSCOPE_ENABLE_ZYNQ=ON
define OSCILL_COPY_DISPLAY
	mkdir -p $(@D)/display
	cp $(BR2_EXTERNAL_OSCILL_PATH)/../display/*.c $(BR2_EXTERNAL_OSCILL_PATH)/../display/*.h $(@D)/display/
endef
OSCILL_POST_RSYNC_HOOKS += OSCILL_COPY_DISPLAY

$(eval $(cmake-package))
