"""Compile the original logo into a coverage mask shared by FSBL and preview.

Run explicitly with Python + Pillow; normal C builds use the checked-in header.
The source PNG is kept unchanged. Its blue ink is rendered white at runtime.
"""
from pathlib import Path

from PIL import Image


HERE = Path(__file__).resolve().parent
source = Image.open(HERE / "boot-logo.png").convert("RGB")
# Blue ink vs neutral paper. Preserve edge coverage, discard the white margin.
rgb = source.tobytes()
ink = [max(0, min(255, round((b - r) * 255 / 70)))
       for r, b in zip(rgb[0::3], rgb[2::3])]
mask = Image.new("L", source.size)
mask.putdata(ink)
mask = mask.crop(mask.point(lambda a: 255 if a > 24 else 0).getbbox())
height = 448
width = round(mask.width * height / mask.height)
mask = mask.resize((width, height), Image.Resampling.LANCZOS)
mask = mask.point(lambda a: round(a / 17) * 17)
data = bytes(mask.tobytes())

# PackBits: high bit selects a repeated byte; otherwise a literal run.
packed = bytearray()
i = 0
while i < len(data):
    run = 1
    while run < 128 and i + run < len(data) and data[i + run] == data[i]:
        run += 1
    if run >= 3:
        packed.extend((128 | (run - 1), data[i]))
        i += run
        continue
    start = i
    i += run
    while i < len(data) and i - start < 128:
        if i + 2 < len(data) and data[i] == data[i + 1] == data[i + 2]:
            break
        i += 1
    packed.append(i - start - 1)
    packed.extend(data[start:i])

lines = ["/* Generated by assets/generate_logo.py from the unchanged source PNG. */",
         f"#define BOOT_LOGO_WIDTH {width}", f"#define BOOT_LOGO_HEIGHT {height}",
         "static const unsigned char boot_logo_data[] = {"]
for i in range(0, len(packed), 20):
    lines.append("    " + ",".join(f"0x{value:02x}" for value in packed[i:i + 20]) + ",")
lines.append("};\n")
(HERE.parent / "boot_logo_data.h").write_text("\n".join(lines), encoding="ascii")
print(f"Logo: {width}x{height}, {len(packed)} bytes packed")
